version: '3'
services:
    web:
        container_name: web
        build: .
        command: gunicorn manage:app --bind 0.0.0.0:5000
        expose:
            - 5000
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgresql://web:password@db:5432/scdiscord
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - FLASK_APP=app/__init__.py
        depends_on:
            - db
        
    db:
        container_name: db
        image: postgres:14-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=web
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=scdiscord
        ports:
            - 5432

    nginx:
        build: ./services/nginx
        ports:
        - 80:80
        depends_on:
        - web

volumes:
    pgdata: